I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 338, in script
    k "Fishiness Levels = 9999%"
ValueError: incomplete format

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 338, in script
    k "Fishiness Levels = 9999%"
  File "/home/hackathon/Documents/renpy-6.99.10-sdk/renpy/ast.py", line 604, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "/home/hackathon/Documents/renpy-6.99.10-sdk/renpy/exports.py", line 1114, in say
    what = what % tag_quoting_dict
ValueError: incomplete format

Linux-4.4.9-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
Ren'Py 6.99.10.1227
MechaWahoo 0.2
